### ISSUE TITLE
How do I sign up?

### ISSUE THREAD

**Issue by joebayles** [mpayson/transit#19]
https://github.com/mpayson/transit/blob/13b2339691c2d20b9bf329b43d455d3c9f8b19ee/src/App.js#L71

Clicking `Sign Up` takes me to [reactstrap](https://github.com/reactstrap/reactstrap).

![fdba1199-4d82-4284-a8a7-d91e8e69c28a](https://user-images.githubusercontent.com/5016557/42166446-0c64a31e-7dd9-11e8-86af-928322cde71c.GIF)

**Comment by mpayson** [comment]
this is still in development, have to copy in Ariel's survey

**Comment by mpayson** [comment]
added link
